# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  branches:
    include:
      - master
      - develop
  tags:
    include:
      - "v*"

pool:
  vmImage: 'windows-latest'

variables:
# must be created in the azure UI under Pipelines > Library and specify accessKey, secretKey, region, and bucket
- group: 's3-public-bucket-upload'
- name: solution
  value: '**/*.sln'
- name: projects
  value: '**/*proj'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'

stages:
  - stage: build
    jobs:
      - job: build
        steps:
        - task: NuGetToolInstaller@1
        
        - task: NuGetCommand@2
          displayName: "restore solutions"
          inputs:
            restoreSolution: '$(solution)'
        
        - task: NuGetCommand@2
          displayName: "restore projects"
          inputs:
            restoreSolution: '$(projects)'
        
        - task: VSBuild@1
          displayName: "build solutions"
          inputs:
            solution: '$(solution)'
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
        
        - task: VSTest@2
          displayName: "execute tests"
          inputs:
            platform: '$(buildPlatform)'
            configuration: '$(buildConfiguration)'
        
        - task: VSBuild@1
          displayName: "build x64 installers"
          inputs:
            solution: 'MorphicSetup\MorphicSetup.wixproj'
            platform: 'x64'
            configuration: '$(buildConfiguration)'
        
        - publish: $(System.DefaultWorkingDirectory)\MorphicSetup\bin\Release\x64\MorphicSetup.msi
          displayName: "save x64 installer for later"
          artifact: x64-installer
          
        - task: VSBuild@1
          displayName: "build x86 installers"
          inputs:
            solution: 'MorphicSetup\MorphicSetup.wixproj'
            platform: 'x86'
            configuration: '$(buildConfiguration)'
            
        - publish: $(System.DefaultWorkingDirectory)\MorphicSetup\bin\Release\x86\MorphicSetup.msi
          displayName: "save x86 installer for later"
          artifact: x86-installer
            
  - stage: upload
    jobs:
      - job: publish_installer
        pool:
          vmImage: "ubuntu-18.04"
        steps:
          # do not checkout code. we only need to upload the published artifact
          - checkout: none
          - download: current
            artifact: x64-installer
          - download: current
            artifact: x86-installer
          - task: Bash@3
            displayName: "upload MSI to s3"
            env:
              AWS_ACCESS_KEY_ID: $(accessKey)
              AWS_SECRET_ACCESS_KEY: $(secretKey)
              BUCKET: $(bucket)
              AWS_DEFAULT_REGION: $(region)
              BRANCH: $(Build.SourceBranch)
              BRANCH_NAME: $(Build.SourceBranchName)
            inputs:
              targetType: 'inline'
              script: |
                set -e
  
                UPLOAD_NAME=""
                if [[ "${BRANCH_NAME}" == "master" ]]; then
                  UPLOAD_NAME="MorphicSetup.msi"
                fi
                if [[ "${BRANCH_NAME}" == "develop" ]]; then
                  UPLOAD_NAME="MorphicSetup-latest.msi"
                fi
                if [[ "${BRANCH}" == *"tags"* ]]; then
                  UPLOAD_NAME="MorphicSetup-${BRANCH_NAME}.msi"
                fi
  
                if [[ "$UPLOAD_NAME" == "" ]]; then
                  echo "no client name found. will not publish to s3"
                  exit 0
                  UPLOAD_NAME="MorphicSetup-selfcontained.msi"
                fi
                set -x
  
                #echo "install AWS CLI"
                #sudo apt-get install -y awscli
  
                ls -al ${AGENT_BUILDDIRECTORY}
                aws s3 cp ${AGENT_BUILDDIRECTORY}/x64-installer/MorphicSetup.msi s3://${BUCKET}/win/x64/$UPLOAD_NAME
                aws s3 cp ${AGENT_BUILDDIRECTORY}/x86-installer/MorphicSetup.msi s3://${BUCKET}/win/x86/$UPLOAD_NAME